version: '2'
services:
    sqlserver:
        image: microsoft/mssql-server-linux:2017-latest
        container_name: sqlserver
        hostname: sqlserver
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Alm0sts3cur3!"
            MSSQL_PID: "Developer"
        ports:
            - "1433:1433"
        volumes:
            - ms-sqlserver-data:/var/opt/mssql
volumes:
    ms-sqlserver-data:
        driver: local